### ISSUE TITLE
CSS Variable for changing the text color when the remove(x) button is hovered

### ISSUE THREAD

**Issue by AjayAntoIsDev** [yairEO/tagify#1211]

**Comment by yairEO** [comment]
Currently there is an `0.5` opacity when the *remove tag* button is hovered:

```css
.tagify__tag__removeBtn:hover + div > span {
    opacity: .5;
}
```

I prefer not to add any color, because many other things can be done here instead of just changing a color so I prefer letting the developers to use the above selector and apply their own custom styles.

For example:

```css
.tagify__tag__removeBtn:hover + div > span {
    filter: blur(2px);
}
```

Yes, I know the selector is fragile, but it does allow writing any properties (not just color).
