### ISSUE TITLE
How to make border around tag larger?

### ISSUE THREAD

**Issue by tomasderner97** [yairEO/tagify#280]
![tag](https://user-images.githubusercontent.com/49766875/62470620-20d2a380-b79b-11e9-88f0-dcddec4947a9.png)

So this doesn't happen?

**Comment by yairEO** [comment]
It's a CSS issue in `.tagify__tag>div::before` regarding the `box-shadow` property. I'll fix this hopefully today and release a new version

**Comment by yairEO** [comment]
How did you get to this situation anyway? Did you change Tagify css?

**Comment by tomasderner97** [comment]
I use bootstrap 4, the input has bootstrap class on it (form-control). But removing the bootstrap class (and form-group) didn't help, the input didn't have round corners anymore but this still happened.

**Comment by yairEO** [comment]
There is some padding on each tag element, coming from somewhere. If you removed the class then simply inspect until you get to the bottom of it.

I clearly see a padding here which is much bigger than what I've intended. If you wish to keep the padding, you can fix this by adding a rule to this selector: 

   .tagify__tag>div::before

https://github.com/yairEO/tagify/blob/master/src/tagify.scss#L150

Simply copy these lines where you see the `box-shadow` and increase the value from `16px` to whatever. Surely `2em` is enough in your situation.

**Comment by shnela** [comment]
@yairEO I had the same problem and adding:
```css
.tagify__tag > div::before {
    box-shadow: 0 0 0 2em var(--tag-hover) inset;
}
```
in my custom css file helped with inactive tags:
![tags1](https://user-images.githubusercontent.com/3773836/62720792-14548200-ba0b-11e9-8388-d3af8697ea55.png)
But I still have problems with style after the mouse is over the tag:
![tags2](https://user-images.githubusercontent.com/3773836/62720825-23d3cb00-ba0b-11e9-9b61-f32613a8b7be.png)

**Comment by yairEO** [comment]
Try changing the tag elements `padding` instead of adjusting the `box-shadow` property

**Comment by shnela** [comment]
I've tried to decrease `padding-top` and `padding-bottom` from .2em to .1em, it helped, but tags were to low.
```css
.tagify__tag > div {
    padding: .15em .5em;
    padding-right: 1.5em;
}
```

Removing `::before` tag from the previous version of style helped:
```css
.tagify__tag > div {
    box-shadow: 0 0 0 2em var(--tag-hover) inset;
}
```
