### ISSUE TITLE
mix-mode does not allow multiline

### ISSUE THREAD

**Issue by yairEO** [yairEO/tagify#317]
This is a regressions caused by this line:

https://github.com/yairEO/tagify/blob/master/src/tagify.scss#L264

----

Also remove:

```css
.tagify__input .tagify__tag {
    line-height: 1.1;
}
```
