### ISSUE TITLE
How to change placholder value?

### ISSUE THREAD

**Issue by kerolloz** [yairEO/tagify#495]
For example
I want the value of the placeholder to be an empty string, when a tag is added.

I tried the following 
```js
tagify.on('add', e => {
  tagify.settings.placeholder = '';
  e.detail.tagify.settings.placeholder = '';
});
```
but it didn't work.

**Comment by yairEO** [comment]
You can do it with CSS only ([demo page](https://jsbin.com/netakiy/1/edit?html,css,js,output))

```css
.tagify__tag + .tagify__input::before{
  display:none
}
```
