### ISSUE TITLE
one line mix mode

### ISSUE THREAD

**Issue by MasoodRezazadeh** [yairEO/tagify#517]
Hi and thanks for this highly customizable library.
is it possible to make text input in mix mode be one line like a normal html input?
im using Tagify in a project where we want to use it in multiple places like  title and description input.

**Comment by yairEO** [comment]
These styles will do it:

```css
.tagify__input {
    white-space: nowrap;
    overflow: auto;
```

**Comment by yairEO** [comment]
wait actually that's not enough. I will need to think how to solve this.

re-opening

**Comment by yairEO** [comment]
```css
.tagify__input {
  white-space: nowrap;
  overflow: auto;
}

.tagify__input br{
  display: none;
}

.tagify__input div{
  display:inline-block;
  white-space: nowrap;
  overflow: auto
  overflow-y:hidden;
}
```
