### ISSUE TITLE
Line height issue with certain fonts

### ISSUE THREAD

**Issue by RichardD2** [yairEO/tagify#768]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### 💥 Demo Page
https://jsfiddle.net/RichardD/rkmgs84t/1/

### Explanation

When using particular fonts and font sizes, having the `line-height` set to `1.1` causes descenders to be obscured - specifically for lower-case letters g, j, p, q, and y. In this specific case, I'm using Bootstrap 4.6, which sets:

```css
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    font-size: 1rem;
}
```

https://jsfiddle.net/RichardD/rkmgs84t/1/
![image](https://user-images.githubusercontent.com/2158265/109959522-88d2ce00-7cdf-11eb-9f62-4454993fadb0.png)

#### Workaround:
Setting `line-height: inherit;` on both the `.tagify` and `.tagify__input::before` rules resolves the problem:

```css
.tagify,
.tagify__input::before {
    line-height: inherit !important;
}
```

https://jsfiddle.net/RichardD/rkmgs84t/2/
![image](https://user-images.githubusercontent.com/2158265/109959557-92f4cc80-7cdf-11eb-9891-a6c65e5e6af5.png)
