### ISSUE TITLE
An invalid form control with name='labels[]' is not focusable.

### ISSUE THREAD

**Issue by engin-can** [yairEO/tagify#783]
Tagify seems to trigger `An invalid form control with name='[NAME OF ATTRIBUTE]' is not focusable.` in Google Chrome for all form fields that have `required` attribute because of `display: none!important;`.

![image](https://user-images.githubusercontent.com/2794116/112788888-bb3ac700-9010-11eb-83c2-3529e84bb11f.png)

**Comment by yairEO** [comment]
Please provide a demo page because I am unaware of such thing and it makes no sense

**Comment by engin-can** [comment]
![image](https://user-images.githubusercontent.com/2794116/112800871-124a9700-9025-11eb-9986-f65bc0e1da28.png)

I'm using Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by engin-can** [comment]
It's simply because you are hiding a required field:

https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

**Comment by yairEO** [comment]
Well this isn't exactly a bug, it's just an annoying error in the *console*

I will change the CSS to:
```css
+ input,
+ textarea{ 
    position: absolute !important;
    left: -9999em !important;
    transform: scale(0) !important;
}
```
