### ISSUE TITLE
Trying to implement dark mode in my site while keeping the same style of Tafigy

### ISSUE THREAD

**Issue by bacloud14** [yairEO/tagify#828]
Particularly, the Scrollbar font color. I am having a hard time to figure out the variable responsible of font color..
For sake of illustration, I have the following CSS for dark mode:

```css
  body.dark {
    --bg-color: rgb(37, 37, 37);
    --font-color: white;
  }
  body.dark .tagify  {
    color: #cccccc;
    /* --input-color: #ffffff !important;
    --tag-text-color--edit: #ffffff !important;
    --tag-text-color: #ffffff !important; */
  }
```
The concerned section is `body.dark .tagify` I have been trying different variables, but none seem to act on scrollbar font color.

The problem is that I am applying style on the whole page for dark mode with font color to be white, and because scrollbar background is already white, I cannot see the text. I want to revert back tagify font color as it is not concerned.

Not to forget, I would like to thank you so much for developing and maintaining this amazing library.
