### ISSUE TITLE
RTL support in mix mode?

### ISSUE THREAD

**Issue by gl0dt** [yairEO/tagify#947]
Hi @yairEO,

I need to display multiple languages on one page and each language has its own tagify component in mix mode, any chance we could have RTL language support in mix mode? I need a `dir ` attributes to set the direction when the language is changed to a RTL language. 

I saw the doc mentions this can be achieved by SCSS, did you mean to change the direction property dynamically?
```css
.tagify .tagify__input {
  direction: rtl;
}
```

Thanks,
