### ISSUE TITLE
Please make the striped background on readonly an opt-out feature

### ISSUE THREAD

**Issue by ROODAY** [yairEO/tagify#974]
For the app my team is working on, we don't want the tags to be striped when set to readonly, as we just want them to render the same way they would when editable. After looking at the source SCSS file and fiddling in a codepen I was able to get rid of the styling with the following CSS override:
```css
.tagify[readonly] > div::before {
  background: var(--tag-bg);
}

.tagify[readonly]:not(.tagify--mix):not(.tagify--select) .tagify__tag > div::before {
  background: var(--tag-bg);
}
```

But it would be nice to be able to set readonly styles through a prop or another CSS variable than having to work around the striping.

**Comment by yairEO** [comment]
This can now be configured using the CSS variable:

### Example:
```css
.tagify{ 
  --readonly-striped: 0; // or 1 to enable
}
```
